// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ctfhagudzlgxxrpnbkbz.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImN0ZmhhZ3VkemxneHhycG5ia2J6Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTg5ODI2NzgsImV4cCI6MjA3NDU1ODY3OH0.AeCJtfGd097NtEXa0LoFgxCX8DG71RcSThDQJa0ibjQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});